before_script:
  - source ~/.bashrc
  - cabal install Parsec hspec hashmap MissingH
stages:
  - build
  - test

job1:
  stage: build
  script: 
    - stack build

job2:
  stage: test
  script: 
    - stack test
