flags: {}
packages:
- .
system-ghc: true
extra-deps:
- HUnit-1.6.0.0
- MissingH-1.4.0.1
- call-stack-0.1.0
- hashable-1.2.7.0
- hashmap-1.3.3
- hslogger-1.2.12
- parsec-3.1.13.0
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
resolver: ghc-8.0.2
