flags: {}
packages:
- .
system-ghc: true
extra-deps:
- HUnit-1.6.0.0
- MissingH-1.4.0.1
- QuickCheck-2.11.3
- algebraic-graphs-0.3
- ansi-terminal-0.8.2
- base-compat-0.10.5
- call-stack-0.1.0
- colour-2.3.4
- generic-deriving-1.12.3
- hashable-1.2.7.0
- hashmap-1.3.3
- hslogger-1.2.12
- hspec-2.4.8
- hspec-core-2.4.8
- hspec-discover-2.4.8
- hspec-expectations-0.8.2
- mtl-2.2.2
- network-2.8.0.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.13.0
- primitive-0.6.4.0
- quickcheck-io-0.2.0
- random-1.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- setenv-0.1.1.3
- stm-2.5.0.0
- text-1.2.3.1
- tf-random-0.5
- th-abstraction-0.2.10.0
resolver: ghc-8.0.2
