flags:
  transformers-compat:
    five: true
packages:
- .
system-ghc: true
extra-deps:
- HUnit-1.6.0.0
- MissingH-1.4.0.1
- QuickCheck-2.11.3
- StateVar-1.1.1.1
- adjunctions-4.4
- algebraic-graphs-0.3
- ansi-terminal-0.8.2
- base-compat-0.10.5
- base-orphans-0.8
- bifunctors-5.5.3
- boxes-0.1.5
- call-stack-0.1.0
- colour-2.3.4
- comonad-5.0.4
- contravariant-1.5
- distributive-0.6
- exceptions-0.10.0
- free-5.1
- generic-deriving-1.12.3
- hashable-1.2.7.0
- hashmap-1.3.3
- hslogger-1.2.12
- hspec-2.4.8
- hspec-core-2.4.8
- hspec-discover-2.4.8
- hspec-expectations-0.8.2
- invariant-0.5.1
- kan-extensions-5.2
- lens-4.17
- mtl-2.2.2
- network-2.8.0.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parallel-3.2.2.0
- parsec-3.1.13.0
- pretty-tree-0.1.0.0
- primitive-0.6.4.0
- profunctors-5.3
- quickcheck-io-0.2.0
- random-1.1
- reflection-2.1.4
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- semigroupoids-5.3.2
- semigroups-0.18.5
- setenv-0.1.1.3
- split-0.2.3.3
- stm-2.5.0.0
- tagged-0.8.6
- text-1.2.3.1
- tf-random-0.5
- th-abstraction-0.2.10.0
- transformers-base-0.4.5.2
- transformers-compat-0.6.2
- unordered-containers-0.2.10.0
- vector-0.12.0.2
- void-0.7.2
- cabal-doctest-1.0.6@sha256:c0b4a5b1ff38d2867e7003b4be59f3bd7e8e204ab8c988d96d3a77472ae671cd
resolver: ghc-8.0.2
