flags: {}
packages:
- .
system-ghc: true
extra-deps: true
- HUnit-1.6.0.0
- MissingH-1.4.0.1
- ansi-terminal-0.8.2
- call-stack-0.1.0
- colour-2.3.4
- hashable-1.2.7.0
- hashmap-1.3.3
- hslogger-1.2.12
- hspec-2.4.8
- hspec-core-2.4.8
- hspec-discover-2.4.8
- hspec-expectations-0.8.2
- parsec-3.1.13.0
- quickcheck-io-0.2.0
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- setenv-0.1.1.3
resolver: ghc-8.0.2
